# ps3.config.yaml

# Mapping from joystick inputs to robot commands

# Axis mapping for linear movement
axis_linear:
  x: 1  # Left stick vertical axis
  y: 0  # Left stick horizontal axis (not used)
  z: -1 # Not used

# scale_linear:
#   x: 1.0 
#   y: 0.0
#   z: 0.0

# Axis mapping for angular movement
axis_angular:
  yaw: 2  # Right stick horizontal axis
  pitch: -1  # Not used
  roll: -1   # Not used

# scale_angular:
#  yaw: 1.0 
#  pitch: 0.0
#  roll: 0.0

# Deadzone for joystick axes
deadzone: 0.01

# Autorepeat rate for buttons (in Hz)
# How often pressed buttons are rechecked for updates
autorepeat_rate: 20.0
